name: "Manif/Update _rsruntime"
on:
    push:
        branches:
          - 'v3.x.x'
        paths:
          - '_rsruntime/**'
          - '_rsruntime/**/*'
    workflow_run:
        workflows: ['Misc/Update Submodules']
        types:
          - completed
    workflow_dispatch:
jobs:
    update_manif:
        uses: ./.github/workflows/update-manifest.yml
        with:
            path: './_rsruntime'
        secrets:
            key: ${{ secrets.MAN_KEY }}