name: "Docs/Generate autodocs"
on:
    push:
        branches:
          - 'v3.x.x'
        paths:
          - '_rsruntime/*.py'
          - '_rsruntime/**/*.py'
    workflow_run:
        workflows: ['Misc/Update Submodules']
        types:
          - completed
    workflow_dispatch:

concurrency:
    group: pull_push_on_${{ github.ref }}

jobs:
    gen_autodocs:
        name: "Generate AutoDocs"
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: "Initialize & update submodules"
            run: |
              git submodule init
              git submodule update
          - uses: actions/setup-python@v4
            with:
                python-version: '3.12'
                cache: pip
          - name: "Remove existing docs"
            run: "rm --force --recursive ./docs/autodocs/"
          - name: "Explicitly install requirements"
            run: "python3 -m pip install -r requirements.txt"
          - name: "Execute makedoc.py"
            run: "python3 ./devel/makedoc.py"
          - name: "Run git status for debugging"
            run: "git status"
          - name: "Commit and push changes"
            uses: EndBug/add-and-commit@v9
            with:
                add: "./docs/autodocs"
                message: "Automatic documentation update (triggered by ${{ github.actor }}: ${{ github.sha }})"
                pull: "--rebase --autostash"