name: Update Manifests
on:
    push:
        branches:
          - 'main'
        paths:
          - '_rsruntime/**'

jobs:
    update_rsruntime_manif:
        name: "Update _rsruntime/MANIFEST.ini"
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
                python-version: '3.12'
                cache: pip
          - name: "Print python3 version"
            run: "python3 --version"
          - name: "Explicitly install requirements"
            run: "python3 -m pip install -r requirements.txt"
          - name: "Extract key"
            env:
                MAN_KEY: ${{ secrets.MAN_KEY }}
            run: |
              echo "$MAN_KEY" | python3 ./devel/pysign.py readinto ./key.pyk
          - name: "Use ./devel/rsruntime-updatemanifest.sh"
            run: "./devel/rsruntime-updatemanifest.sh 2>&1 /dev/null"
          - name: "Remove key"
            run: "rm ./key.pyk"
          - name: "Commit and push changes"
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                commit_message: "Automatic manifest update (triggered by ${{ github.actor }}: ${{ github.sha }})"