name: Update Manifests
on:
    push:
        branches:
          - 'v3.x.x'
        paths:
          - '_rsruntime/**'
          - '_rsruntime/**/*'
          - '_rsplugins/1000-builtin/**'
          - '_rsplugins/1000-builtin/**/*'
    workflow_dispatch:
jobs:
    filter_paths:
        name: "Check which paths need updating"
        runs-on: ubuntu-latest
        outputs:
            rsruntime: ${{ steps.filter_paths.outputs.rsruntime }}
            plugins_builtin: ${{ steps.filter_paths.outputs.plugins_builtin }}
        steps:
          - uses: actions/checkout@v3
          - uses: dorny/paths-filter@v2
            id: filter_paths
            with:
                filters: |
                    rsruntime:
                      - '_rsruntime/**'
                      - '_rsruntime/**/*'
                    rsplugins_builtin:
                      - '_rsplugins/1000-builtin/**'
                      - '_rsplugins/1000-builtin/**/*'

    update_manif:
        needs: filter_paths
        strategy:
            matrix:
                manif:
                  - {path: '_rsruntime', do: '${{ needs.filter_path_outputs.rsruntime }}'}
                  - {path': '_rsplugins/1000-builtin', do: '${{ needs.filter_path.outputs.rsplugins_builtin }}'}
        name: "Update manifest for ${{ matrix.manif.path }}"
        if: ${{ needs.filter_paths.outputs[matrix.manif.id] }}
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
                python-version: '3.12'
                cache: pip
          - name: "Print python3 version"
            run: "python3 --version"
          - name: "Explicitly install requirements"
            run: "python3 -m pip install -r requirements.txt"
          - name: "Extract key"
            env:
                MAN_KEY: ${{ secrets.MAN_KEY }}
            run: |
              echo "$MAN_KEY" | python3 ./devel/pysign.py readinto ./key.pyk
          - name: "Update manifest"
            env:
                MAN_PATH: ${{ matrix.manif.path }}
            run: |
              python3 ./devel/mkmanifest.py update "$MAN_PATH/MANIFEST.ini" "$MAN_PATH/" --overwrite
          - name: "Sign manifest"
            env:
                MAN_PATH: ${{ matrix.manif.path }}
            run: |
              python3 ./devel/mkmanifest.py sign "$MAN_PATH/MANIFEST.ini" ./key.pyk --overwrite
          - name: "Remove key"
            run: "rm ./key.pyk"
          - name: "Commit and push changes"
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                commit_message: "Automatic manifest update for ${{ matrix.manif.path }} (triggered by ${{ github.actor }}: ${{ github.sha }})"
