name: "Misc/Update Submodules"
on:
    workflow_dispatch:

jobs:
    update-submodules:
        name: "Update submodules"
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: "Pull and update submodules"
            run: |
              git submodule update --init --recursive
              git submodule update --recursive --remote
          - name: "Commit and push changes"
            run: |
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com
              git config user.name github-actions
              git commit -am "Updated submodules"
              git push